typography_spectrum: 0.622156519908458
content_rating:
  adult: false
color:
  brandStrength: 0.5703989763278514
  lightness: 0.2811164369340986
  saturation: 0.6183888104278594
  rhythmicContrast: 0.42700966098345816
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.9708034689538181
author:
  name: Joe Hazard
  email: joevallee@gmail.com
  url: 'https://thegrid.ai/the-hazard-group/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/36e31941-1f16-47a9-ab78-e9ec00bd2b2c.gif
name: THE HAZARD GROUP
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b6d316a1-1aad-40bb-a9f8-7b13b081815e.gif
description: Imagine
